// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.6
// source: idl/message_enum.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageType int32

const (
	MessageType_HEART_BEAT      MessageType = 0
	MessageType_ONLINE          MessageType = 1
	MessageType_LIST_USERS      MessageType = 2
	MessageType_SEND_MESSAGE    MessageType = 3
	MessageType_OFFLINE         MessageType = 4
	MessageType_RECEIVE_MESSAGE MessageType = 5
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "HEART_BEAT",
		1: "ONLINE",
		2: "LIST_USERS",
		3: "SEND_MESSAGE",
		4: "OFFLINE",
		5: "RECEIVE_MESSAGE",
	}
	MessageType_value = map[string]int32{
		"HEART_BEAT":      0,
		"ONLINE":          1,
		"LIST_USERS":      2,
		"SEND_MESSAGE":    3,
		"OFFLINE":         4,
		"RECEIVE_MESSAGE": 5,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_idl_message_enum_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_idl_message_enum_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_idl_message_enum_proto_rawDescGZIP(), []int{0}
}

type MessageState int32

const (
	MessageState_Sent      MessageState = 0
	MessageState_DELIVERED MessageState = 1
	MessageState_Seen      MessageState = 2
)

// Enum value maps for MessageState.
var (
	MessageState_name = map[int32]string{
		0: "Sent",
		1: "DELIVERED",
		2: "Seen",
	}
	MessageState_value = map[string]int32{
		"Sent":      0,
		"DELIVERED": 1,
		"Seen":      2,
	}
)

func (x MessageState) Enum() *MessageState {
	p := new(MessageState)
	*p = x
	return p
}

func (x MessageState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageState) Descriptor() protoreflect.EnumDescriptor {
	return file_idl_message_enum_proto_enumTypes[1].Descriptor()
}

func (MessageState) Type() protoreflect.EnumType {
	return &file_idl_message_enum_proto_enumTypes[1]
}

func (x MessageState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageState.Descriptor instead.
func (MessageState) EnumDescriptor() ([]byte, []int) {
	return file_idl_message_enum_proto_rawDescGZIP(), []int{1}
}

var File_idl_message_enum_proto protoreflect.FileDescriptor

var file_idl_message_enum_proto_rawDesc = []byte{
	0x0a, 0x16, 0x69, 0x64, 0x6c, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x65, 0x6e,
	0x75, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x2a, 0x6d, 0x0a, 0x0b,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0e, 0x0a, 0x0a, 0x48,
	0x45, 0x41, 0x52, 0x54, 0x5f, 0x42, 0x45, 0x41, 0x54, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x4f,
	0x4e, 0x4c, 0x49, 0x4e, 0x45, 0x10, 0x01, 0x12, 0x0e, 0x0a, 0x0a, 0x4c, 0x49, 0x53, 0x54, 0x5f,
	0x55, 0x53, 0x45, 0x52, 0x53, 0x10, 0x02, 0x12, 0x10, 0x0a, 0x0c, 0x53, 0x45, 0x4e, 0x44, 0x5f,
	0x4d, 0x45, 0x53, 0x53, 0x41, 0x47, 0x45, 0x10, 0x03, 0x12, 0x0b, 0x0a, 0x07, 0x4f, 0x46, 0x46,
	0x4c, 0x49, 0x4e, 0x45, 0x10, 0x04, 0x12, 0x13, 0x0a, 0x0f, 0x52, 0x45, 0x43, 0x45, 0x49, 0x56,
	0x45, 0x5f, 0x4d, 0x45, 0x53, 0x53, 0x41, 0x47, 0x45, 0x10, 0x05, 0x2a, 0x31, 0x0a, 0x0c, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x53,
	0x65, 0x6e, 0x74, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x44, 0x45, 0x4c, 0x49, 0x56, 0x45, 0x52,
	0x45, 0x44, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x53, 0x65, 0x65, 0x6e, 0x10, 0x02, 0x42, 0x06,
	0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_idl_message_enum_proto_rawDescOnce sync.Once
	file_idl_message_enum_proto_rawDescData = file_idl_message_enum_proto_rawDesc
)

func file_idl_message_enum_proto_rawDescGZIP() []byte {
	file_idl_message_enum_proto_rawDescOnce.Do(func() {
		file_idl_message_enum_proto_rawDescData = protoimpl.X.CompressGZIP(file_idl_message_enum_proto_rawDescData)
	})
	return file_idl_message_enum_proto_rawDescData
}

var file_idl_message_enum_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_idl_message_enum_proto_goTypes = []interface{}{
	(MessageType)(0),  // 0: pb.MessageType
	(MessageState)(0), // 1: pb.MessageState
}
var file_idl_message_enum_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_idl_message_enum_proto_init() }
func file_idl_message_enum_proto_init() {
	if File_idl_message_enum_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_idl_message_enum_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_idl_message_enum_proto_goTypes,
		DependencyIndexes: file_idl_message_enum_proto_depIdxs,
		EnumInfos:         file_idl_message_enum_proto_enumTypes,
	}.Build()
	File_idl_message_enum_proto = out.File
	file_idl_message_enum_proto_rawDesc = nil
	file_idl_message_enum_proto_goTypes = nil
	file_idl_message_enum_proto_depIdxs = nil
}
